FROM openjdk:11-jre-slim

ENV JAVA_ENV=PRODUCTION
ENV KUMULUZEE_ENV_NAME=prod
ENV KUMULUZEE_ENV_PROD=true
ENV KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/products
ENV KUMULUZEE_DATASOURCES0_USERNAME=postgres
ENV KUMULUZEE_DATASOURCES0_PASSWORD=postgres
ENV KUMULUZEE_LOGS_LOGGERS0_LEVEL=INFO

RUN mkdir /app
WORKDIR /app

ADD ./api/v1/target/products-service.jar /app

EXPOSE 8080

CMD ["java", "-jar", "products-service.jar"]
